name: Lynx
main: marvtech.lynx.Lynx
version: 0.1
api-version: '1.20'
folia-supported: true
commands:
  country:
    description: Country management
  faction:
    description: Faction management
  lynx:
    description: Lynx utilities
  admin:
    description: Admin commands
